### ISSUE TITLE
Impl HttpConnection for tokio_rustls::TlsStream

### ISSUE THREAD

**Issue by samscott89** [hyperium/http-connection#1]
Fairly self-explanatory.

Expect to see a PR shortly...

**Comment by LucioFranco** [comment]
I left a comment in #2

**Comment by samscott89** [comment]
I'm gonna pull the discussion here:

https://github.com/hyperium/http-connection/pull/2#issuecomment-490959732
> 
> 
> @samscott89 this is something I actually wanted to avoid and instead was going to include this in `tower-http-tls` with a wrapper struct since add this dep to this crate is not needed. In fact this crate is async agnostic. You can still expose the inner type via `get_ref`, `get_mut` and `into_inner`.
> 
> I am a bit short on time if you want to help move that tower-http-tls forward :)

I had a quick look at the open PR - https://github.com/tower-rs/tower-http/pull/19

I can start helping out on that one. I'm not entirely sure I see the distinction between `tokio_tcp::TcpStream` implementing `HttpConnection` but not `TlsStream`. I mostly just did this as a panic reaction to `cargo update` breaking all my code since `tower_hyper` needs something which implements `HttpConnection` :)

I guess I'm not entirely sure what the point of this library is, if it's not to be implemented on things like `TlsStream`? Is the idea that it's on the library writer to write a wrapper for `TlsStream` which implements `HttpConnection`?

**Comment by LucioFranco** [comment]
@samscott89 so for tower-hyper you can wrap the TLSStream like I did in that PR. The reason I dont want it in here is because I dont want to bring in deps. This crate is mostly just to have a stable trait that can be the "glue". tokio-tcp is implemented behind a feature flag that is enabled by default because most use cases of this will be with that stream.

The issue with the tls stream is that maybe you want to use rustls or you want to use native-tls crate, this doesnt force you to bring either of those deps. We really want this to be as light as possible.

**Comment by samscott89** [comment]
Closing as out of scope then :)
